# Generated by Django 3.2.8 on 2021-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaState3', '0002_auto_20211018_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='deductions',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
